---
services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
    volumes:
      - ./qdrant_data:/qdrant/storage—ç
    networks:
      - my_network
  app:
    build: ./
    ports:
        - 7861:7861
    volumes:
        - ./:/usr/src/
    networks:
      - my_network
    environment:
      - GRADIO_SERVER_NAME="0.0.0.0"
      - GRADIO_SERVER_PORT=7861
    depends_on:
      - qdrant

networks:
  my_network:
    driver: bridge

 
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
# volumes:
#   weaviate_data:
# ...