---
services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - my_network
  laiws:
    image: georgechufff/laiws:latest
    build: ./
    ports:
        - 7860:7860
    volumes:
        - ./:/usr/src/
    networks:
      - my_network
    depends_on:
      - qdrant

networks:
  my_network:
    driver: bridge